package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name="contrato"
    ,schema="pribantsa"
)
public class Contrato  implements java.io.Serializable {


     private int idContrato;
     private Empleado empleado;
     private TipoContrato tipoContrato;
     private Date fechaInicio;
     private Date fechaFin;

    public Contrato() {
    }

    public Contrato(int idContrato, Empleado empleado, TipoContrato tipoContrato, Date fechaInicio, Date fechaFin) {
       this.idContrato = idContrato;
       this.empleado = empleado;
       this.tipoContrato = tipoContrato;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
     @Id 

    
    @Column(name="id_contrato", unique=true, nullable=false)
    public int getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoContrato", nullable=false)
    public TipoContrato getTipoContrato() {
        return this.tipoContrato;
    }
    
    public void setTipoContrato(TipoContrato tipoContrato) {
        this.tipoContrato = tipoContrato;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=13)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


