package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Correo generated by hbm2java
 */
@Entity
@Table(name="correo"
    ,schema="pribantsa"
)
public class Correo  implements java.io.Serializable {


     private int idCorreo;
     private Empleado empleado;
     private String correo;

    public Correo() {
    }

    public Correo(int idCorreo, Empleado empleado, String correo) {
       this.idCorreo = idCorreo;
       this.empleado = empleado;
       this.correo = correo;
    }
   
     @Id 

    
    @Column(name="id_correo", unique=true, nullable=false)
    public int getIdCorreo() {
        return this.idCorreo;
    }
    
    public void setIdCorreo(int idCorreo) {
        this.idCorreo = idCorreo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="correo", nullable=false)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


