package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Criterio generated by hbm2java
 */
@Entity
@Table(name="criterio"
    ,schema="pribantsa"
)
public class Criterio  implements java.io.Serializable {


     private int idCriterio;
     private PuestoTrabajo puestoTrabajo;
     private String descripcion;
     private int peso;
     private Set evaluacions = new HashSet(0);

    public Criterio() {
    }

	
    public Criterio(int idCriterio, PuestoTrabajo puestoTrabajo, String descripcion, int peso) {
        this.idCriterio = idCriterio;
        this.puestoTrabajo = puestoTrabajo;
        this.descripcion = descripcion;
        this.peso = peso;
    }
    public Criterio(int idCriterio, PuestoTrabajo puestoTrabajo, String descripcion, int peso, Set evaluacions) {
       this.idCriterio = idCriterio;
       this.puestoTrabajo = puestoTrabajo;
       this.descripcion = descripcion;
       this.peso = peso;
       this.evaluacions = evaluacions;
    }
   
     @Id 

    
    @Column(name="id_criterio", unique=true, nullable=false)
    public int getIdCriterio() {
        return this.idCriterio;
    }
    
    public void setIdCriterio(int idCriterio) {
        this.idCriterio = idCriterio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPuesto", nullable=false)
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="peso", nullable=false)
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="criterio")
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }




}


