package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Descuento generated by hbm2java
 */
@Entity
@Table(name="descuento"
    ,schema="pribantsa"
)
public class Descuento  implements java.io.Serializable {


     private int idDescuento;
     private Empleado empleado;
     private TipoDescuento tipoDescuento;
     private Date fecha;

    public Descuento() {
    }

    public Descuento(int idDescuento, Empleado empleado, TipoDescuento tipoDescuento, Date fecha) {
       this.idDescuento = idDescuento;
       this.empleado = empleado;
       this.tipoDescuento = tipoDescuento;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="id_descuento", unique=true, nullable=false)
    public int getIdDescuento() {
        return this.idDescuento;
    }
    
    public void setIdDescuento(int idDescuento) {
        this.idDescuento = idDescuento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoDescuento", nullable=false)
    public TipoDescuento getTipoDescuento() {
        return this.tipoDescuento;
    }
    
    public void setTipoDescuento(TipoDescuento tipoDescuento) {
        this.tipoDescuento = tipoDescuento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


