package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Educacion generated by hbm2java
 */
@Entity
@Table(name="educacion"
    ,schema="pribantsa"
)
public class Educacion  implements java.io.Serializable {


     private int idEducacion;
     private Empleado empleado;
     private String titulo;
     private Date fechaInicio;
     private Date fechaFin;
     private String institucion;

    public Educacion() {
    }

	
    public Educacion(int idEducacion, Empleado empleado, String titulo, Date fechaInicio, Date fechaFin) {
        this.idEducacion = idEducacion;
        this.empleado = empleado;
        this.titulo = titulo;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public Educacion(int idEducacion, Empleado empleado, String titulo, Date fechaInicio, Date fechaFin, String institucion) {
       this.idEducacion = idEducacion;
       this.empleado = empleado;
       this.titulo = titulo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.institucion = institucion;
    }
   
     @Id 

    
    @Column(name="id_educacion", unique=true, nullable=false)
    public int getIdEducacion() {
        return this.idEducacion;
    }
    
    public void setIdEducacion(int idEducacion) {
        this.idEducacion = idEducacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="titulo", nullable=false)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=13)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="institucion")
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }




}


