package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evaluacion generated by hbm2java
 */
@Entity
@Table(name="evaluacion"
    ,schema="pribantsa"
)
public class Evaluacion  implements java.io.Serializable {


     private int idEvaluacion;
     private Empleado empleado;
     private Criterio criterio;
     private double puntaje;
     private Date fecha;

    public Evaluacion() {
    }

    public Evaluacion(int idEvaluacion, Empleado empleado, Criterio criterio, double puntaje, Date fecha) {
       this.idEvaluacion = idEvaluacion;
       this.empleado = empleado;
       this.criterio = criterio;
       this.puntaje = puntaje;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="id_evaluacion", unique=true, nullable=false)
    public int getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(int idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCriterio", nullable=false)
    public Criterio getCriterio() {
        return this.criterio;
    }
    
    public void setCriterio(Criterio criterio) {
        this.criterio = criterio;
    }

    
    @Column(name="puntaje", nullable=false, precision=17, scale=17)
    public double getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


