package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Objetivo generated by hbm2java
 */
@Entity
@Table(name="objetivo"
    ,schema="pribantsa"
)
public class Objetivo  implements java.io.Serializable {


     private int idObjetivo;
     private PuestoTrabajo puestoTrabajo;
     private String descripcion;
     private boolean alcance;

    public Objetivo() {
    }

    public Objetivo(int idObjetivo, PuestoTrabajo puestoTrabajo, String descripcion, boolean alcance) {
       this.idObjetivo = idObjetivo;
       this.puestoTrabajo = puestoTrabajo;
       this.descripcion = descripcion;
       this.alcance = alcance;
    }
   
     @Id 

    
    @Column(name="id_objetivo", unique=true, nullable=false)
    public int getIdObjetivo() {
        return this.idObjetivo;
    }
    
    public void setIdObjetivo(int idObjetivo) {
        this.idObjetivo = idObjetivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPuestoTrabajo", nullable=false)
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="alcance", nullable=false)
    public boolean isAlcance() {
        return this.alcance;
    }
    
    public void setAlcance(boolean alcance) {
        this.alcance = alcance;
    }




}


