package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Planilla generated by hbm2java
 */
@Entity
@Table(name="planilla"
    ,schema="pribantsa"
)
public class Planilla  implements java.io.Serializable {


     private int idPlanilla;
     private Empleado empleado;
     private Date fechaInicio;
     private Date fechaFin;
     private double diasTrabajados;
     private double horas;
     private double salarioDevengado;
     private double extrasDiurnas;
     private double extrasNocturnas;
     private double feriado;
     private double totalDescuentos;
     private double liquidoPagar;

    public Planilla() {
    }

    public Planilla(int idPlanilla, Empleado empleado, Date fechaInicio, Date fechaFin, double diasTrabajados, double horas, double salarioDevengado, double extrasDiurnas, double extrasNocturnas, double feriado, double totalDescuentos, double liquidoPagar) {
       this.idPlanilla = idPlanilla;
       this.empleado = empleado;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.diasTrabajados = diasTrabajados;
       this.horas = horas;
       this.salarioDevengado = salarioDevengado;
       this.extrasDiurnas = extrasDiurnas;
       this.extrasNocturnas = extrasNocturnas;
       this.feriado = feriado;
       this.totalDescuentos = totalDescuentos;
       this.liquidoPagar = liquidoPagar;
    }
   
     @Id 

    
    @Column(name="id_planilla", unique=true, nullable=false)
    public int getIdPlanilla() {
        return this.idPlanilla;
    }
    
    public void setIdPlanilla(int idPlanilla) {
        this.idPlanilla = idPlanilla;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=13)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="dias_trabajados", nullable=false, precision=17, scale=17)
    public double getDiasTrabajados() {
        return this.diasTrabajados;
    }
    
    public void setDiasTrabajados(double diasTrabajados) {
        this.diasTrabajados = diasTrabajados;
    }

    
    @Column(name="horas", nullable=false, precision=17, scale=17)
    public double getHoras() {
        return this.horas;
    }
    
    public void setHoras(double horas) {
        this.horas = horas;
    }

    
    @Column(name="salario_devengado", nullable=false, precision=17, scale=17)
    public double getSalarioDevengado() {
        return this.salarioDevengado;
    }
    
    public void setSalarioDevengado(double salarioDevengado) {
        this.salarioDevengado = salarioDevengado;
    }

    
    @Column(name="extras_diurnas", nullable=false, precision=17, scale=17)
    public double getExtrasDiurnas() {
        return this.extrasDiurnas;
    }
    
    public void setExtrasDiurnas(double extrasDiurnas) {
        this.extrasDiurnas = extrasDiurnas;
    }

    
    @Column(name="extras_nocturnas", nullable=false, precision=17, scale=17)
    public double getExtrasNocturnas() {
        return this.extrasNocturnas;
    }
    
    public void setExtrasNocturnas(double extrasNocturnas) {
        this.extrasNocturnas = extrasNocturnas;
    }

    
    @Column(name="feriado", nullable=false, precision=17, scale=17)
    public double getFeriado() {
        return this.feriado;
    }
    
    public void setFeriado(double feriado) {
        this.feriado = feriado;
    }

    
    @Column(name="total_descuentos", nullable=false, precision=17, scale=17)
    public double getTotalDescuentos() {
        return this.totalDescuentos;
    }
    
    public void setTotalDescuentos(double totalDescuentos) {
        this.totalDescuentos = totalDescuentos;
    }

    
    @Column(name="liquido_pagar", nullable=false, precision=17, scale=17)
    public double getLiquidoPagar() {
        return this.liquidoPagar;
    }
    
    public void setLiquidoPagar(double liquidoPagar) {
        this.liquidoPagar = liquidoPagar;
    }




}


