package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PuestoTrabajo generated by hbm2java
 */
@Entity
@Table(name="puesto_trabajo"
    ,schema="pribantsa"
)
public class PuestoTrabajo  implements java.io.Serializable {


     private int idPuestoTrabajo;
     private String nombre;
     private String descripcion;
     private double salarioMax;
     private double salarioMin;
     private Set objetivos = new HashSet(0);
     private Set empleados = new HashSet(0);
     private Set criterios = new HashSet(0);
     private Set tipoBonos = new HashSet(0);
     private Set puestoHistoricos = new HashSet(0);

    public PuestoTrabajo() {
    }

	
    public PuestoTrabajo(int idPuestoTrabajo, String nombre, String descripcion, double salarioMax, double salarioMin) {
        this.idPuestoTrabajo = idPuestoTrabajo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.salarioMax = salarioMax;
        this.salarioMin = salarioMin;
    }
    public PuestoTrabajo(int idPuestoTrabajo, String nombre, String descripcion, double salarioMax, double salarioMin, Set objetivos, Set empleados, Set criterios, Set tipoBonos, Set puestoHistoricos) {
       this.idPuestoTrabajo = idPuestoTrabajo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.salarioMax = salarioMax;
       this.salarioMin = salarioMin;
       this.objetivos = objetivos;
       this.empleados = empleados;
       this.criterios = criterios;
       this.tipoBonos = tipoBonos;
       this.puestoHistoricos = puestoHistoricos;
    }
   
     @Id 

    
    @Column(name="id_puesto_trabajo", unique=true, nullable=false)
    public int getIdPuestoTrabajo() {
        return this.idPuestoTrabajo;
    }
    
    public void setIdPuestoTrabajo(int idPuestoTrabajo) {
        this.idPuestoTrabajo = idPuestoTrabajo;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="salario_max", nullable=false, precision=17, scale=17)
    public double getSalarioMax() {
        return this.salarioMax;
    }
    
    public void setSalarioMax(double salarioMax) {
        this.salarioMax = salarioMax;
    }

    
    @Column(name="salario_min", nullable=false, precision=17, scale=17)
    public double getSalarioMin() {
        return this.salarioMin;
    }
    
    public void setSalarioMin(double salarioMin) {
        this.salarioMin = salarioMin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="puestoTrabajo")
    public Set getObjetivos() {
        return this.objetivos;
    }
    
    public void setObjetivos(Set objetivos) {
        this.objetivos = objetivos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="puestoTrabajo")
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="puestoTrabajo")
    public Set getCriterios() {
        return this.criterios;
    }
    
    public void setCriterios(Set criterios) {
        this.criterios = criterios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="puestoTrabajo")
    public Set getTipoBonos() {
        return this.tipoBonos;
    }
    
    public void setTipoBonos(Set tipoBonos) {
        this.tipoBonos = tipoBonos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="puestoTrabajo")
    public Set getPuestoHistoricos() {
        return this.puestoHistoricos;
    }
    
    public void setPuestoHistoricos(Set puestoHistoricos) {
        this.puestoHistoricos = puestoHistoricos;
    }




}


