package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PuestoHistorico generated by hbm2java
 */
@Entity
@Table(name="puesto_historico"
    ,schema="pribantsa"
)
public class PuestoHistorico  implements java.io.Serializable {


     private int idHistoricoPuesto;
     private Empleado empleado;
     private PuestoTrabajo puestoTrabajo;
     private Date fechaInicio;
     private Date fechaFin;

    public PuestoHistorico() {
    }

	
    public PuestoHistorico(int idHistoricoPuesto, Empleado empleado, PuestoTrabajo puestoTrabajo, Date fechaInicio) {
        this.idHistoricoPuesto = idHistoricoPuesto;
        this.empleado = empleado;
        this.puestoTrabajo = puestoTrabajo;
        this.fechaInicio = fechaInicio;
    }
    public PuestoHistorico(int idHistoricoPuesto, Empleado empleado, PuestoTrabajo puestoTrabajo, Date fechaInicio, Date fechaFin) {
       this.idHistoricoPuesto = idHistoricoPuesto;
       this.empleado = empleado;
       this.puestoTrabajo = puestoTrabajo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
     @Id 

    
    @Column(name="id_historico_puesto", unique=true, nullable=false)
    public int getIdHistoricoPuesto() {
        return this.idHistoricoPuesto;
    }
    
    public void setIdHistoricoPuesto(int idHistoricoPuesto) {
        this.idHistoricoPuesto = idHistoricoPuesto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPuesto", nullable=false)
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", length=13)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


