package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sancion generated by hbm2java
 */
@Entity
@Table(name="sancion"
    ,schema="pribantsa"
)
public class Sancion  implements java.io.Serializable {


     private int idSancion;
     private Empleado empleado;
     private int gravedad;
     private String descripcion;
     private Date fecha;

    public Sancion() {
    }

    public Sancion(int idSancion, Empleado empleado, int gravedad, String descripcion, Date fecha) {
       this.idSancion = idSancion;
       this.empleado = empleado;
       this.gravedad = gravedad;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="id_sancion", unique=true, nullable=false)
    public int getIdSancion() {
        return this.idSancion;
    }
    
    public void setIdSancion(int idSancion) {
        this.idSancion = idSancion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="gravedad", nullable=false)
    public int getGravedad() {
        return this.gravedad;
    }
    
    public void setGravedad(int gravedad) {
        this.gravedad = gravedad;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


