package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name="tipo_contrato"
    ,schema="pribantsa"
)
public class TipoContrato  implements java.io.Serializable {


     private int idTipoContrato;
     private String descripcion;
     private Set contratos = new HashSet(0);

    public TipoContrato() {
    }

	
    public TipoContrato(int idTipoContrato, String descripcion) {
        this.idTipoContrato = idTipoContrato;
        this.descripcion = descripcion;
    }
    public TipoContrato(int idTipoContrato, String descripcion, Set contratos) {
       this.idTipoContrato = idTipoContrato;
       this.descripcion = descripcion;
       this.contratos = contratos;
    }
   
     @Id 

    
    @Column(name="id_tipo_contrato", unique=true, nullable=false)
    public int getIdTipoContrato() {
        return this.idTipoContrato;
    }
    
    public void setIdTipoContrato(int idTipoContrato) {
        this.idTipoContrato = idTipoContrato;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoContrato")
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


