package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDescuento generated by hbm2java
 */
@Entity
@Table(name="tipo_descuento"
    ,schema="pribantsa"
)
public class TipoDescuento  implements java.io.Serializable {


     private int idTipoDescuento;
     private String descripcion;
     private double porcentaje;
     private Set descuentos = new HashSet(0);

    public TipoDescuento() {
    }

	
    public TipoDescuento(int idTipoDescuento, String descripcion, double porcentaje) {
        this.idTipoDescuento = idTipoDescuento;
        this.descripcion = descripcion;
        this.porcentaje = porcentaje;
    }
    public TipoDescuento(int idTipoDescuento, String descripcion, double porcentaje, Set descuentos) {
       this.idTipoDescuento = idTipoDescuento;
       this.descripcion = descripcion;
       this.porcentaje = porcentaje;
       this.descuentos = descuentos;
    }
   
     @Id 

    
    @Column(name="id_tipo_descuento", unique=true, nullable=false)
    public int getIdTipoDescuento() {
        return this.idTipoDescuento;
    }
    
    public void setIdTipoDescuento(int idTipoDescuento) {
        this.idTipoDescuento = idTipoDescuento;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="porcentaje", nullable=false, precision=17, scale=17)
    public double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoDescuento")
    public Set getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Set descuentos) {
        this.descuentos = descuentos;
    }




}


