package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name="transaccion"
    ,schema="pribantsa"
)
public class Transaccion  implements java.io.Serializable {


     private int idTransaccion;
     private Empleado empleado;
     private boolean creditoDebito;
     private double monto;
     private Date fecha;

    public Transaccion() {
    }

    public Transaccion(int idTransaccion, Empleado empleado, boolean creditoDebito, double monto, Date fecha) {
       this.idTransaccion = idTransaccion;
       this.empleado = empleado;
       this.creditoDebito = creditoDebito;
       this.monto = monto;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="id_transaccion", unique=true, nullable=false)
    public int getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(int idTransaccion) {
        this.idTransaccion = idTransaccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="credito_debito", nullable=false)
    public boolean isCreditoDebito() {
        return this.creditoDebito;
    }
    
    public void setCreditoDebito(boolean creditoDebito) {
        this.creditoDebito = creditoDebito;
    }

    
    @Column(name="monto", nullable=false, precision=17, scale=17)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=29)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


