package com.pribantsa.demo;
// Generated 04-10-2015 12:03:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacacion generated by hbm2java
 */
@Entity
@Table(name="vacacion"
    ,schema="pribantsa"
)
public class Vacacion  implements java.io.Serializable {


     private int idVacacion;
     private Empleado empleado;
     private Date fechaInicio;
     private Date fechaFin;

    public Vacacion() {
    }

	
    public Vacacion(int idVacacion, Empleado empleado, Date fechaInicio) {
        this.idVacacion = idVacacion;
        this.empleado = empleado;
        this.fechaInicio = fechaInicio;
    }
    public Vacacion(int idVacacion, Empleado empleado, Date fechaInicio, Date fechaFin) {
       this.idVacacion = idVacacion;
       this.empleado = empleado;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
     @Id 

    
    @Column(name="id_vacacion", unique=true, nullable=false)
    public int getIdVacacion() {
        return this.idVacacion;
    }
    
    public void setIdVacacion(int idVacacion) {
        this.idVacacion = idVacacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", length=13)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


