package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Criterio generated by hbm2java
 */
public class Criterio  implements java.io.Serializable {


     private int idCriterio;
     private PuestoTrabajo puestoTrabajo;
     private String descripcion;
     private int peso;
     private Set evaluacions = new HashSet(0);

    public Criterio() {
    }

	
    public Criterio(int idCriterio, PuestoTrabajo puestoTrabajo, String descripcion, int peso) {
        this.idCriterio = idCriterio;
        this.puestoTrabajo = puestoTrabajo;
        this.descripcion = descripcion;
        this.peso = peso;
    }
    public Criterio(int idCriterio, PuestoTrabajo puestoTrabajo, String descripcion, int peso, Set evaluacions) {
       this.idCriterio = idCriterio;
       this.puestoTrabajo = puestoTrabajo;
       this.descripcion = descripcion;
       this.peso = peso;
       this.evaluacions = evaluacions;
    }
   
    public int getIdCriterio() {
        return this.idCriterio;
    }
    
    public void setIdCriterio(int idCriterio) {
        this.idCriterio = idCriterio;
    }
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }




}


