package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Educacion generated by hbm2java
 */
public class Educacion  implements java.io.Serializable {


     private int idEducacion;
     private Empleado empleado;
     private String titulo;
     private Date fecha;
     private String lugar;
     private String institucion;
     private String idx;
     private String nivel;

    public Educacion() {
    }

	
    public Educacion(int idEducacion, Empleado empleado, String titulo, Date fecha) {
        this.idEducacion = idEducacion;
        this.empleado = empleado;
        this.titulo = titulo;
        this.fecha = fecha;
    }
    public Educacion(int idEducacion, Empleado empleado, String titulo, Date fecha, String lugar, String institucion, String idx, String nivel) {
       this.idEducacion = idEducacion;
       this.empleado = empleado;
       this.titulo = titulo;
       this.fecha = fecha;
       this.lugar = lugar;
       this.institucion = institucion;
       this.idx = idx;
       this.nivel = nivel;
    }
   
    public int getIdEducacion() {
        return this.idEducacion;
    }
    
    public void setIdEducacion(int idEducacion) {
        this.idEducacion = idEducacion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public String getIdx() {
        return this.idx;
    }
    
    public void setIdx(String idx) {
        this.idx = idx;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }




}


