package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int empleadoId;
     private PuestoTrabajo puestoTrabajo;
     private String dui;
     private String isss;
     private String afp;
     private String sexo;
     private int idDepartamento;
     private String nit;
     private String nombre;
     private String apellido;
     private String cuenta;
     private double salario;
     private Integer edad;
     private String estadoCivil;
     private Integer idManager;
     private Integer idx;
     private Set sancions = new HashSet(0);
     private Set descuentos = new HashSet(0);
     private Set telefonos = new HashSet(0);
     private Set expLaborals = new HashSet(0);
     private Set reconocimientos = new HashSet(0);
     private Set correos = new HashSet(0);
     private Set puestoHistoricos = new HashSet(0);
     private Set vacacions = new HashSet(0);
     private Set bonos = new HashSet(0);
     private Set educacions = new HashSet(0);
     private Set permisos = new HashSet(0);
     private Set evaluacions = new HashSet(0);
     private Set contratos = new HashSet(0);
     private Set capacitacions = new HashSet(0);
     private Set planillas = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int empleadoId, PuestoTrabajo puestoTrabajo, String dui, String isss, String afp, int idDepartamento, String nit, String nombre, String apellido, String cuenta, double salario) {
        this.empleadoId = empleadoId;
        this.puestoTrabajo = puestoTrabajo;
        this.dui = dui;
        this.isss = isss;
        this.afp = afp;
        this.idDepartamento = idDepartamento;
        this.nit = nit;
        this.nombre = nombre;
        this.apellido = apellido;
        this.cuenta = cuenta;
        this.salario = salario;
    }
    public Empleado(int empleadoId, PuestoTrabajo puestoTrabajo, String dui, String isss, String afp, String sexo, int idDepartamento, String nit, String nombre, String apellido, String cuenta, double salario, Integer edad, String estadoCivil, Integer idManager, Integer idx, Set sancions, Set descuentos, Set telefonos, Set expLaborals, Set reconocimientos, Set correos, Set puestoHistoricos, Set vacacions, Set bonos, Set educacions, Set permisos, Set evaluacions, Set contratos, Set capacitacions, Set planillas) {
       this.empleadoId = empleadoId;
       this.puestoTrabajo = puestoTrabajo;
       this.dui = dui;
       this.isss = isss;
       this.afp = afp;
       this.sexo = sexo;
       this.idDepartamento = idDepartamento;
       this.nit = nit;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cuenta = cuenta;
       this.salario = salario;
       this.edad = edad;
       this.estadoCivil = estadoCivil;
       this.idManager = idManager;
       this.idx = idx;
       this.sancions = sancions;
       this.descuentos = descuentos;
       this.telefonos = telefonos;
       this.expLaborals = expLaborals;
       this.reconocimientos = reconocimientos;
       this.correos = correos;
       this.puestoHistoricos = puestoHistoricos;
       this.vacacions = vacacions;
       this.bonos = bonos;
       this.educacions = educacions;
       this.permisos = permisos;
       this.evaluacions = evaluacions;
       this.contratos = contratos;
       this.capacitacions = capacitacions;
       this.planillas = planillas;
    }
   
    public int getEmpleadoId() {
        return this.empleadoId;
    }
    
    public void setEmpleadoId(int empleadoId) {
        this.empleadoId = empleadoId;
    }
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getIsss() {
        return this.isss;
    }
    
    public void setIsss(String isss) {
        this.isss = isss;
    }
    public String getAfp() {
        return this.afp;
    }
    
    public void setAfp(String afp) {
        this.afp = afp;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Integer getIdManager() {
        return this.idManager;
    }
    
    public void setIdManager(Integer idManager) {
        this.idManager = idManager;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }
    public Set getSancions() {
        return this.sancions;
    }
    
    public void setSancions(Set sancions) {
        this.sancions = sancions;
    }
    public Set getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Set descuentos) {
        this.descuentos = descuentos;
    }
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }
    public Set getExpLaborals() {
        return this.expLaborals;
    }
    
    public void setExpLaborals(Set expLaborals) {
        this.expLaborals = expLaborals;
    }
    public Set getReconocimientos() {
        return this.reconocimientos;
    }
    
    public void setReconocimientos(Set reconocimientos) {
        this.reconocimientos = reconocimientos;
    }
    public Set getCorreos() {
        return this.correos;
    }
    
    public void setCorreos(Set correos) {
        this.correos = correos;
    }
    public Set getPuestoHistoricos() {
        return this.puestoHistoricos;
    }
    
    public void setPuestoHistoricos(Set puestoHistoricos) {
        this.puestoHistoricos = puestoHistoricos;
    }
    public Set getVacacions() {
        return this.vacacions;
    }
    
    public void setVacacions(Set vacacions) {
        this.vacacions = vacacions;
    }
    public Set getBonos() {
        return this.bonos;
    }
    
    public void setBonos(Set bonos) {
        this.bonos = bonos;
    }
    public Set getEducacions() {
        return this.educacions;
    }
    
    public void setEducacions(Set educacions) {
        this.educacions = educacions;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }
    public Set getCapacitacions() {
        return this.capacitacions;
    }
    
    public void setCapacitacions(Set capacitacions) {
        this.capacitacions = capacitacions;
    }
    public Set getPlanillas() {
        return this.planillas;
    }
    
    public void setPlanillas(Set planillas) {
        this.planillas = planillas;
    }




}


