package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion  implements java.io.Serializable {


     private int idEvaluacion;
     private Empleado empleado;
     private Criterio criterio;
     private double puntaje;
     private Date fecha;
     private Integer idx;

    public Evaluacion() {
    }

	
    public Evaluacion(int idEvaluacion, Empleado empleado, Criterio criterio, double puntaje, Date fecha) {
        this.idEvaluacion = idEvaluacion;
        this.empleado = empleado;
        this.criterio = criterio;
        this.puntaje = puntaje;
        this.fecha = fecha;
    }
    public Evaluacion(int idEvaluacion, Empleado empleado, Criterio criterio, double puntaje, Date fecha, Integer idx) {
       this.idEvaluacion = idEvaluacion;
       this.empleado = empleado;
       this.criterio = criterio;
       this.puntaje = puntaje;
       this.fecha = fecha;
       this.idx = idx;
    }
   
    public int getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(int idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Criterio getCriterio() {
        return this.criterio;
    }
    
    public void setCriterio(Criterio criterio) {
        this.criterio = criterio;
    }
    public double getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


