package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0



/**
 * ExpLaboral generated by hbm2java
 */
public class ExpLaboral  implements java.io.Serializable {


     private long idExplaboral;
     private Empleado empleado;
     private String lugar;
     private Integer tiempo;
     private String cargo;
     private Integer idx;

    public ExpLaboral() {
    }

	
    public ExpLaboral(long idExplaboral) {
        this.idExplaboral = idExplaboral;
    }
    public ExpLaboral(long idExplaboral, Empleado empleado, String lugar, Integer tiempo, String cargo, Integer idx) {
       this.idExplaboral = idExplaboral;
       this.empleado = empleado;
       this.lugar = lugar;
       this.tiempo = tiempo;
       this.cargo = cargo;
       this.idx = idx;
    }
   
    public long getIdExplaboral() {
        return this.idExplaboral;
    }
    
    public void setIdExplaboral(long idExplaboral) {
        this.idExplaboral = idExplaboral;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Integer getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(Integer tiempo) {
        this.tiempo = tiempo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


