package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Planilla generated by hbm2java
 */
public class Planilla  implements java.io.Serializable {


     private int idPlanilla;
     private Empleado empleado;
     private Date fechaInicio;
     private Date fechaFin;
     private Double diasTrabajados;
     private Double horas;
     private Double extrasDiurnas;
     private Double extrasNocturnas;
     private Double feriado;
     private Double salarioDevengado;
     private Double descuentos;

    public Planilla() {
    }

	
    public Planilla(int idPlanilla, Empleado empleado, Date fechaInicio, Date fechaFin) {
        this.idPlanilla = idPlanilla;
        this.empleado = empleado;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public Planilla(int idPlanilla, Empleado empleado, Date fechaInicio, Date fechaFin, Double diasTrabajados, Double horas, Double extrasDiurnas, Double extrasNocturnas, Double feriado, Double salarioDevengado, Double descuentos) {
       this.idPlanilla = idPlanilla;
       this.empleado = empleado;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.diasTrabajados = diasTrabajados;
       this.horas = horas;
       this.extrasDiurnas = extrasDiurnas;
       this.extrasNocturnas = extrasNocturnas;
       this.feriado = feriado;
       this.salarioDevengado = salarioDevengado;
       this.descuentos = descuentos;
    }
   
    public int getIdPlanilla() {
        return this.idPlanilla;
    }
    
    public void setIdPlanilla(int idPlanilla) {
        this.idPlanilla = idPlanilla;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Double getDiasTrabajados() {
        return this.diasTrabajados;
    }
    
    public void setDiasTrabajados(Double diasTrabajados) {
        this.diasTrabajados = diasTrabajados;
    }
    public Double getHoras() {
        return this.horas;
    }
    
    public void setHoras(Double horas) {
        this.horas = horas;
    }
    public Double getExtrasDiurnas() {
        return this.extrasDiurnas;
    }
    
    public void setExtrasDiurnas(Double extrasDiurnas) {
        this.extrasDiurnas = extrasDiurnas;
    }
    public Double getExtrasNocturnas() {
        return this.extrasNocturnas;
    }
    
    public void setExtrasNocturnas(Double extrasNocturnas) {
        this.extrasNocturnas = extrasNocturnas;
    }
    public Double getFeriado() {
        return this.feriado;
    }
    
    public void setFeriado(Double feriado) {
        this.feriado = feriado;
    }
    public Double getSalarioDevengado() {
        return this.salarioDevengado;
    }
    
    public void setSalarioDevengado(Double salarioDevengado) {
        this.salarioDevengado = salarioDevengado;
    }
    public Double getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Double descuentos) {
        this.descuentos = descuentos;
    }




}


