package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PuestoHistorico generated by hbm2java
 */
public class PuestoHistorico  implements java.io.Serializable {


     private int idHistoricoPuesto;
     private PuestoTrabajo puestoTrabajo;
     private Empleado empleado;
     private Date fechaInicio;
     private Date fechaFin;

    public PuestoHistorico() {
    }

	
    public PuestoHistorico(int idHistoricoPuesto, PuestoTrabajo puestoTrabajo, Empleado empleado, Date fechaInicio) {
        this.idHistoricoPuesto = idHistoricoPuesto;
        this.puestoTrabajo = puestoTrabajo;
        this.empleado = empleado;
        this.fechaInicio = fechaInicio;
    }
    public PuestoHistorico(int idHistoricoPuesto, PuestoTrabajo puestoTrabajo, Empleado empleado, Date fechaInicio, Date fechaFin) {
       this.idHistoricoPuesto = idHistoricoPuesto;
       this.puestoTrabajo = puestoTrabajo;
       this.empleado = empleado;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public int getIdHistoricoPuesto() {
        return this.idHistoricoPuesto;
    }
    
    public void setIdHistoricoPuesto(int idHistoricoPuesto) {
        this.idHistoricoPuesto = idHistoricoPuesto;
    }
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


