package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0



/**
 * Reconocimiento generated by hbm2java
 */
public class Reconocimiento  implements java.io.Serializable {


     private int idReconocimiento;
     private Empleado empleado;
     private String descripcion;
     private Integer idx;

    public Reconocimiento() {
    }

	
    public Reconocimiento(int idReconocimiento, Empleado empleado, String descripcion) {
        this.idReconocimiento = idReconocimiento;
        this.empleado = empleado;
        this.descripcion = descripcion;
    }
    public Reconocimiento(int idReconocimiento, Empleado empleado, String descripcion, Integer idx) {
       this.idReconocimiento = idReconocimiento;
       this.empleado = empleado;
       this.descripcion = descripcion;
       this.idx = idx;
    }
   
    public int getIdReconocimiento() {
        return this.idReconocimiento;
    }
    
    public void setIdReconocimiento(int idReconocimiento) {
        this.idReconocimiento = idReconocimiento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


