package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Sancion generated by hbm2java
 */
public class Sancion  implements java.io.Serializable {


     private int idSancion;
     private Empleado empleado;
     private int gravedad;
     private String descripcion;
     private Date fecha;
     private Integer idx;

    public Sancion() {
    }

	
    public Sancion(int idSancion, Empleado empleado, int gravedad, String descripcion, Date fecha) {
        this.idSancion = idSancion;
        this.empleado = empleado;
        this.gravedad = gravedad;
        this.descripcion = descripcion;
        this.fecha = fecha;
    }
    public Sancion(int idSancion, Empleado empleado, int gravedad, String descripcion, Date fecha, Integer idx) {
       this.idSancion = idSancion;
       this.empleado = empleado;
       this.gravedad = gravedad;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.idx = idx;
    }
   
    public int getIdSancion() {
        return this.idSancion;
    }
    
    public void setIdSancion(int idSancion) {
        this.idSancion = idSancion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public int getGravedad() {
        return this.gravedad;
    }
    
    public void setGravedad(int gravedad) {
        this.gravedad = gravedad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


