package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0



/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private int idTelefono;
     private Empleado empleado;
     private String telefono;
     private Integer idx;

    public Telefono() {
    }

	
    public Telefono(int idTelefono, Empleado empleado, String telefono) {
        this.idTelefono = idTelefono;
        this.empleado = empleado;
        this.telefono = telefono;
    }
    public Telefono(int idTelefono, Empleado empleado, String telefono, Integer idx) {
       this.idTelefono = idTelefono;
       this.empleado = empleado;
       this.telefono = telefono;
       this.idx = idx;
    }
   
    public int getIdTelefono() {
        return this.idTelefono;
    }
    
    public void setIdTelefono(int idTelefono) {
        this.idTelefono = idTelefono;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


