package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0



/**
 * TipoBono generated by hbm2java
 */
public class TipoBono  implements java.io.Serializable {


     private int idTipoBono;
     private PuestoTrabajo puestoTrabajo;
     private double porcentaje;
     private Integer idx;

    public TipoBono() {
    }

	
    public TipoBono(int idTipoBono, PuestoTrabajo puestoTrabajo, double porcentaje) {
        this.idTipoBono = idTipoBono;
        this.puestoTrabajo = puestoTrabajo;
        this.porcentaje = porcentaje;
    }
    public TipoBono(int idTipoBono, PuestoTrabajo puestoTrabajo, double porcentaje, Integer idx) {
       this.idTipoBono = idTipoBono;
       this.puestoTrabajo = puestoTrabajo;
       this.porcentaje = porcentaje;
       this.idx = idx;
    }
   
    public int getIdTipoBono() {
        return this.idTipoBono;
    }
    
    public void setIdTipoBono(int idTipoBono) {
        this.idTipoBono = idTipoBono;
    }
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }
    public double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


