package com.pribantsa.pojo;
// Generated 05-26-2015 11:50:05 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Vacacion generated by hbm2java
 */
public class Vacacion  implements java.io.Serializable {


     private int idVacacion;
     private Empleado empleado;
     private Date fechaInicio;
     private Date fechaFin;
     private Integer idx;

    public Vacacion() {
    }

	
    public Vacacion(int idVacacion, Empleado empleado, Date fechaInicio) {
        this.idVacacion = idVacacion;
        this.empleado = empleado;
        this.fechaInicio = fechaInicio;
    }
    public Vacacion(int idVacacion, Empleado empleado, Date fechaInicio, Date fechaFin, Integer idx) {
       this.idVacacion = idVacacion;
       this.empleado = empleado;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.idx = idx;
    }
   
    public int getIdVacacion() {
        return this.idVacacion;
    }
    
    public void setIdVacacion(int idVacacion) {
        this.idVacacion = idVacacion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


